# -*- coding: utf-8 -*-
"""01_data_cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5jse5ROV0QyPM496jEZu57UgztFWo5B
"""

"""
Cleans the original EIA dataset and produces Cleaned_Dataset.csv
"""

import pandas as pd

# Load raw data
df = pd.read_excel("../DATA/Original_Dataset.xlsx")

# Remove empty rows
df = df[~df["Unnamed: 1"].isna()]

# Rename columns using header row
for col_idx in range(len(df.columns)):
    new_name = df[df.columns[col_idx]].iloc[0]
    df = df.rename(columns={df.columns[col_idx]: new_name})

# Remove extra header rows
df = df.drop(df.index[:2])

# Convert Month to Date
df["Date"] = pd.to_datetime(df["Month"], format="%Y %B", errors="coerce")

# Select relevant columns
clean_df = df.iloc[:, [1, 3, 9, 11, 13]].copy()

# Save cleaned dataset
clean_df.to_csv("../DATA/Cleaned_Dataset.csv", index=False)

print("Cleaned_Dataset.csv created")