# -*- coding: utf-8 -*-
"""02_eda_starter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vY-I9bCgGz9CTXvUNal2InthglbwV7LE
"""

"""
Starter code for performing exploratory data analysis
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load cleaned dataset
df = pd.read_csv("../DATA/Cleaned_Dataset.csv")
df["Date"] = pd.to_datetime(df["Date"])

# Preview data
print(df.head())
print(df.describe())

# Example starter:
# plt.plot(df["Date"], df["Total Renewable Energy Production"])
# plt.title("Starter Plot: Renewable Energy Production Over Time")
# plt.show()